version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "image-recognition"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gx2gy3vtogos"
s3_prefix = "image-recognition"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = true
image_repositories = []
