version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-for-free"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gx2gy3vtogos"
s3_prefix = "aws-for-free"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"api\""
image_repositories = []
