AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  login inputs and returnd them as json

Resources:
  AllLoggingFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 100
      MemorySize: 1024
      Events:
        FreeAwsLabsApi:
          Type: Api 
          Properties:
            Path: /
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/joke/"
